
name: FreeBSD Test

on: 
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    # env:
    #   MYTOKEN : ${{ secrets.MYTOKEN }}
    #   MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        release: '13.4'
        usesh: true
        prepare: |
          pkg install -y curl protobuf gmake rust libgsasl openssl

        run: |
          pwd
          cargo build



